
# Site settings
title: HS BLOG
name: Hyeonseop Jeong
email: "21600665@handong.edu"
job: "CS Undergraduate at Handong Global University"
description: > # this means to ignore newlines until "baseurl:"
  2020년도 하반기부터 공부한 내용을 정리하기 위해 만든 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://hyeonseopjeong.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  HyeonseopJeong
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

owner:
  
  #avatar: leonids-logo.png
  
  bio:
  
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: HyeonseopJeong
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram:  #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
